### ISSUE TITLE
patches for latest kernels...

### ISSUE THREAD

**Issue by burrezo** [jorgem-seq/NVIDIA-Linux-304.137-patches#1]
Hi Jorge,

First of all, thank you for your great work!!, I've used your patches to make old nvidia cards works with Debian 10 Buster ( http://forums.debian.net/viewtopic.php?f=5&t=144257&p=730543#p730543 ) and Antix 19.3 ( https://www.antixforum.com/forums/topic/nvidia-geforce-6800-antix-19-2-32bit/#post-45180 ).

Can you update patches for new kernels (5.8... 5.9...)??

Best regards.

**Comment by burrezo** [comment]
MX-Linux19.3_64: https://forum.mxlinux.org/viewtopic.php?p=608559#p608559

**Comment by burrezo** [comment]
Linux Mint 20 64bits xfce: https://forums.linuxmint.com/viewtopic.php?f=59&t=335583

**Comment by jorgem-seq** [comment]
Hi I'm glad that the patches worked for you the links are a very neat step-by-step.
About 5.8+ support I think that for old systems would be better to stick with 5.4 LTS, starting with recent versions a lot of legacy code was removed so no I won't update the repo.

**Comment by burrezo** [comment]
Understood, thank you for your answer!

**Comment by Alexandre20323453** [comment]
This script knows the correct patches depending on the kernel version.
local: NVIDIA-Linux-304.137-patches/patches 
@jorgem-seq 

https://pastebin.com/raw/Bn5s7hfz

*Sorry, but I don't know how to put code here

**Comment by burrezo** [comment]
Thank you Alexandre20323453!!

**Comment by jorgem-seq** [comment]
Closing issue before archiving.
